services:
  mymvcapp:
    build:
      context: .
      dockerfile: Dockerfile
      network: host   
    container_name: dotnet_app_mymvcapp
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=interactiveboardentities;Username=postgres;Password=228228228
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=Europe/Moscow
    ports:
      - "8082:8082"
    networks:
      - shared_db_net

 


networks:
  shared_db_net:
    external: true    
